---
# ansible-playbook prepare_igel_icg.yml -i inventories/ICG/hosts.yml --vault-password-file ~/.vault_pass.txt

- hosts: ICG_Server

  tags:
    - user

  vars:
    ansible_user: "{{ base_user }}"
    ansible_password: "{{ base_user_password }}"
    ansible_sudo_pass: "{{ base_sudo_pass }}"

    # robertdebock.users
    users_user_list:
      - name: root
        password: "{{ root_password | string | password_hash('sha512', 'SecretSalt') }}"
      - name: "{{ default_user }}"
        sudo_options: "ALL=(ALL) NOPASSWD: ALL"
        authorized_keys:
          - "{{ id_rsa_pub }}"

  become: true

  roles:
    - robertdebock.users

  tasks:
    - name: Change password for {{default_user}}
      user:
        name: "{{default_user}}"
        password: "{{ default_user_password | string | password_hash('sha512', 'SecretSalt') }}"

- hosts: ICG_Server

  tags:
    - system

  vars:
    # robertdebock.bootstrap
    bootstrap_user: "{{ default_user }}"
    bootstrap_wait_for_host: yes

    # robertdebock.ntp
    ntp_timezone: Europe/Berlin

    # robertdebock.locale
    locale_lang: de_DE.UTF-8
    locale_timezone: Europe/Berlin

    # weareinteractive.openssl
    openssl_keys:
      - name: "{{ ssl_key_name }}"
        key: "{{ ssl_key }}"
    openssl_certs:
      - name: "{{ ssl_crt_name }}"
        cert: "{{ ssl_crt }}"
    openssl_keys_path: /etc/ssl/private
    openssl_certs_path: /etc/ssl/private
    openssl_default_key_owner: root
    openssl_default_key_group: root
    openssl_default_cert_owner: root
    openssl_default_cert_group: root
    openssl_cacert_import: yes

    # weareinteractive.vsftpd
    vsftpd_users:
      - username: ftpuser
        name: FTP User
        home: /ums_filetransfer
        password: "{{ ftpuser_password }}"
    vsftpd_key_file: "{{ ssl_key_name }}"
    vsftpd_cert_file: "{{ ssl_crt_name }}"
    vsftpd_config:
      force_local_data_ssl: YES
      force_local_logins_ssl: YES
      ftpd_banner: "{{ ftpd_banner }}"
      ssl_enable: YES
      ssl_tlsv1: YES
      local_umask: "002"
      local_enable: YES
      write_enable: YES
      chroot_local_user: YES
      xferlog_enable: YES
      log_ftp_protocol: YES
      allow_writeable_chroot: YES
      pasv_enable: YES
      pasv_max_port: "{{ pasv_max_port }}"
      pasv_min_port: "{{ pasv_min_port }}"
      allow_anon_ssl: NO
      ssl_sslv2: NO
      ssl_sslv3: NO
      require_ssl_reuse: NO
      ssl_ciphers: HIGH
      pasv_addr_resolve: YES
      pasv_address: "{{ pasv_address }}"

    # robertdebock.firewall
    firewall_default_rule: allow
    firewall_services:
      - name: ssh
      - name: 8443
        protocol: tcp
      - name: 21
        protocol: tcp
      - name: "{{ pasv_min_port }}:{{ pasv_max_port }}"
        protocol: tcp

    # geerlingguy.security
    security_vsftpd_port: 21
    security_fail2ban_custom_configuration_template: files/ssh_vsftpd_jail.local.j2

  become: true

  roles:
    - robertdebock.bootstrap
    - robertdebock.update
    - robertdebock.auto_update
    - robertdebock.ntp
    - robertdebock.locale
    - robertdebock.hostname
    - weareinteractive.openssl
    - weareinteractive.vsftpd
    - robertdebock.firewall
    - geerlingguy.security

- hosts: ICG_Server

  tags:
    - icg

  vars:
    igelicg_url: http://fwu.igel.com/files/IGEL_CLOUD_GATEWAY/
    igelicg_bin: installer-2.02.110.bin
    igelicg_keystore_icg: files/keystore.icg
    instdir: "/tmp"

  become: true

  tasks:
    - name: "Download ICG binary"
      get_url:
        url: "{{ igelicg_url }}{{ igelicg_bin }}"
        dest: "{{ instdir }}"
        mode: "0755"

    - name: "Copy keystore.icg"
      copy:
        src: "{{ igelicg_keystore_icg }}"
        dest: "{{ instdir }}"
        mode: "0755"

    - debug:
        msg:
          - "1. Connect to the host as root (alternative: sudo -s)"
          - "2. cd /tmp"
          - "3. ./{{ igelicg_bin }} keystore.icg"
          - "4. Follow wizard"
          - "5. rm {{ igelicg_bin }} keystore.icg"
          - "6. UMS Console -> UMS Administration -> IGEL Cloud Gateway -> Add existing Gateway to database"
