---
- name: "Download ICG binary"
  get_url:
    url: "{{ igelicg_base_url }}/{{ igelicg_bin }}"
    dest: "{{ igelicg_dl_dir }}"
    mode: "0755"

- name: "Copy keystore.icg"
  copy:
    src: "{{ igelicg_keystore_dir }}/{{ igelicg_keystore_icg }}"
    dest: "{{ igelicg_dl_dir }}"
    mode: "0755"

- name: "manual steps necessary to install ICG"
  debug:
    msg: |
      - 1. Connect to the host as root (alternative: sudo -s)
      - 2. cd /tmp
      - 3. ./{{ igelicg_bin }} {{ igelicg_keystore_icg }}
      - 4. Follow wizard
      - 5. rm {{ igelicg_bin }} {{ igelicg_keystore_icg }}
      - 6. UMS Console -> UMS Administration -> IGEL Cloud Gateway -> Add existing Gateway to database
