---
# general
ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

# base image user
base_user: "username"
base_user_password: "password"
base_sudo_pass: "password"

# ansible user
ansible_user: "username"
ansible_user_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  ...

# default user
default_user: username
default_user_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  ...

# root user
root_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  ...

# default authorized key
default_authorized_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  ...

# default privat key
default_id_rsa: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  ...

# default public key
default_id_rsa_pub: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  ...

# robertdebock.bootstrap
bootstrap_user: "{{ default_user }}"
bootstrap_wait_for_host: yes

# robertdebock.users
users_user_list:
  - name: root
    password: "{{ root_password | string | password_hash('sha512', 'SecretSalt') }}"
  - name: "{{ default_user }}"
    sudo_options: "ALL=(ALL) NOPASSWD: ALL"
    authorized_keys:
      - "{{ default_authorized_key }}"

# weareinteractive.openssl
openssl_keys:
  - name: "{{ ssl_key_name }}"
    key: "{{ ssl_key }}"
openssl_certs:
  - name: "{{ ssl_crt_name }}"
    cert: "{{ ssl_crt }}"
openssl_keys_path: /etc/ssl/private
openssl_certs_path: /etc/ssl/private
openssl_default_key_owner: root
openssl_default_key_group: root
openssl_default_cert_owner: root
openssl_default_cert_group: root
openssl_cacert_import: yes

# weareinteractive.vsftpd
vsftpd_users:
  - username: "{{ ftpuser }}"
    name: FTP User
    home: /ums_filetransfer
    password: "{{ ftpuser_password }}"
vsftpd_key_file: "{{ ssl_key_name }}"
vsftpd_cert_file: "{{ ssl_crt_name }}"
vsftpd_config:
  force_local_data_ssl: YES
  force_local_logins_ssl: YES
  ftpd_banner: "{{ ftpd_banner }}"
  ssl_enable: YES
  ssl_tlsv1: YES
  local_umask: "002"
  local_enable: YES
  write_enable: YES
  chroot_local_user: YES
  xferlog_enable: YES
  log_ftp_protocol: YES
  allow_writeable_chroot: YES
  pasv_enable: YES
  pasv_max_port: "{{ vsftpd_max_port }}"
  pasv_min_port: "{{ vsftpd_min_port }}"
  allow_anon_ssl: NO
  ssl_sslv2: NO
  ssl_sslv3: NO
  require_ssl_reuse: NO
  ssl_ciphers: HIGH
  pasv_addr_resolve: YES
  pasv_address: "{{ icg_fqdn }}"
  data_connection_timeout: 1200

# robertdebock.ntp
ntp_timezone: Europe/Berlin

# robertdebock.locale
locale_lang: de_DE.UTF-8
locale_timezone: Europe/Berlin

# weareinteractive.openssl
ssl_crt_name: acme.com.crt
ssl_crt: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  ...

ssl_key_name: acme.com.key
ssl_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  ...

# robertdebock.vsftpd / robertdebock.firewall
ftpd_banner: ICG ACME CORP
ftpuser: ftpuser
ftpuser_password_vault: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  ...

## mkpasswd --method=sha-512
ftpuser_password: $...

# rheinwerk.install_root_ca_certs
root_ca_url: "https://www.acme.com/certificates/"
root_cas:
  - "RootCA.crt"
  - "IssuingCA01.crt"
  - "IssuingCA02.crt"

# ICG general
icg_fqdn: icg.acme.com
